### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RelTakeover** [Fantasy-Agario/ProjectOmega#1]
when i write node index.js , said that:

![image](https://cloud.githubusercontent.com/assets/19374681/21287746/b5677a9c-c451-11e6-8f9e-4f36cdae4faf.png)

**Comment by Fantasy-Agario** [comment]
Ooops sorry I'll fix it :D

**Comment by Fantasy-Agario** [comment]
@RelTakeover Fixed it :P

Sorry for the inconvenience .
